FROM node:latest
WORKDIR /code
RUN npm install -g @vue/cli && npm install -g @vue/cli-service-global && npm install -g @vue/cli-service && npm install -g axios bootstrap-vue vuex vue-router
ADD . /code/


